### PR TITLE
AddElevatorIDSigns command and fix to keypad indicators

### PR DESCRIPTION
**Pull request by MultiMonorail**
Here’s a new command that adds Elevator ID signs, good for Destination Dispatch elevators. I also made it so that the keypad indicator shows an error if a floor isn’t selected due to different factors.

EDIT: I’m not sure if the one involving LimitQueue fully works, so I may need to test it later before this is merged.

### CODE REVIEW

**Comment by MultiMonorail** [comment]
I'm actually going to reopen this now, however, I still don't have a fix for the LimitQueue factor within Requested(). Here's what needs to be fixed:

Right now, in an elevator with a keypad and with LimitQueue turned on, if I enter in a destination, the indicator will say that the call has been requested. However, if I enter another destination in the same direction, the indicator will show an error even though the call has been selected. The indicator should've shown that the call has been requested in this case.

**Comment by eventhorizon5** [comment]
I merged the changes with a cleanup too, I mainly removed the backwards-compatibility code from the new script command, since it's a new command.  You can also leave the pull requests open if you're still working on them, no need to close them.

**Comment by eventhorizon5** [comment]
I managed to fix the issue you were mentioning.  I gave the Requested() function a floor parameter, and then use that in the LimitQueue IF statement.  I mainly found the issue while running the debugger, do you have debugging set up on your system?  (I had issues getting that to work in Windows before).  I recently made a new build system for Skyscraper on Windows which you could use, I just have to write up the instructions for it.

**Comment by MultiMonorail** [comment]
I don't think I have debugging set up on my system. 

I also tested what you put in, and it's working good. I also found a couple of things as well regarding the LimitQueue IF statement:

The first one is that the indicator will say that a call has been requested on a floor that the elevator is passing or departing when I enter that floor again. I was able to fix this with this IF statement:
`else if (e->LimitQueue == true && e->IsMoving == true && floor == GetFloor())`
	`KeypadError();`

I'm giving this one to you through comments so that you can put it in, because the branch has conflicts and I don't want to mess with anything that might cause issues.

The second one is that if I go to an intermediate floor and input a floor in the opposite direction without any more floors queued in the direction that I just went in, the indicator will show an error even though the floor has been picked.
Example for the Simple building: I input and go up to floor 3. Once I arrive, if I input that I want to go to floor 1, the indicator will show XX, but the floor will be selected.

**Comment by eventhorizon5** [comment]
I'll check that issue.  It's much easier to test issues while debugging, and here's a guide I wrote up just now on how to set up Skyscraper with the new build system, and also how to get the app to run in debug mode.  Let me know if this guide works for you, and if so, I'll add it to the compiling doc.  The old build system is very broken, so I wanted to get the new one working before the 2.0 release if possible.

[install.txt](https://github.com/user-attachments/files/16655923/install.txt)

**Comment by eventhorizon5** [comment]
I updated the install guide with some fixes, use this one instead:
[install2.txt](https://github.com/user-attachments/files/16656703/install2.txt)

**Comment by eventhorizon5** [comment]
The issue you mentioned has been fixed - I just remade the queue size checks that you had before.

**Comment by MultiMonorail** [comment]
> I updated the install guide with some fixes, use this one instead: [install2.txt](https://github.com/user-attachments/files/16656703/install2.txt)

I'm currently trying this, but I can't find the c:/bullet/include/bullet folder within the bullet zip that I downloaded.

**Comment by eventhorizon5** [comment]
I think it needs to be set to c:/bullet/include - I had multiple builds so it seemed to be different for each one.

**Comment by MultiMonorail** [comment]
Still doesn't work for me. I'm getting these errors:

`CMake Error at C:/Program Files/CMake/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find Bullet (missing: BULLET_CONVEX_DECOMPOSITION)` 

`Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.30/Modules/FindPackageHandleStandardArgs.cmake:603 (_FPHSA_FAILURE_MESSAGE)
  tools/cmake/FindBullet.cmake:76 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:61 (find_package)`

**Comment by eventhorizon5** [comment]
Did you set each of the Bullet libraries in there (like the BULLET_CONVEX_DECOMPOSITION variable?  It mainly can't find Bullet, so you have to set the variables manually.

**Comment by MultiMonorail** [comment]
I didn't do that, I just did that and it's all working now. How exactly did you test the issue? I want know for future reference so that it'll be easier for me to figure out what's wrong with any new stuff I'm doing.

EDIT: Never mind, I was able to search it up on how to do it.

**Comment by eventhorizon5** [comment]
Changes for this are in the latest build, so I'll close the PR.

**Pull request closed without merging**
